language: shell
services:
- docker
dist: xenial
jobs:
  include:
  - stage: Build & Publish Images
    os: linux
    arch: s390x
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=debian
    script: "make publish-images-variant"
  - os: linux
    arch: ppc64le
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=debian
    script: "make publish-images-variant"
  - os: linux
    arch: amd64
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=debian
    script: "make publish-images-variant"
  - os: linux
    arch: arm64
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=debian
    script: "make publish-images-variant"
  - os: linux
    arch: s390x
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=alpine
    script: "make publish-images-variant"
  - os: linux
    arch: ppc64le
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=alpine
    script: "make publish-images-variant"
  - os: linux
    arch: amd64
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=alpine
    script: "make publish-images-variant"
  - os: linux
    arch: arm64
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=alpine
    script: "make publish-images-variant"
  - os: linux
    arch: s390x
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=slim
    script: "make publish-images-variant"
  - os: linux
    arch: ppc64le
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=slim
    script: "make publish-images-variant"
  - os: linux
    arch: amd64
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=slim
    script: "make publish-images-variant"
  - os: linux
    arch: arm64
    env: ARCH=${TRAVIS_CPU_ARCH} VARIANT=slim
    script: "make publish-images-variant"
  - stage: Publish Tags
    os: linux
    arch: amd64
    script: "make publish-tags-debian"
  - os: linux
    arch: amd64
    script: "make publish-tag-alpine"
  - os: linux
    arch: amd64
    script: "make publish-tags-slim"
  - os: linux
    arch: amd64
    script: "make publish-tags-lts-debian"
  - os: linux
    arch: amd64
    script: "make publish-tag-lts-alpine"
  - os: linux
    arch: amd64
    script: "make publish-tags-lts-slim"
  - os: linux
    arch: amd64
    script: "make publish-tag-latest"
  - stage: Publish Manifests
    os: linux
    arch: amd64
    script: "make publish-manifests-debian"
  - os: linux
    arch: amd64
    script: "make publish-manifests-alpine"
  - os: linux
    arch: amd64
    script: "make publish-manifests-slim"
  - os: linux
    arch: amd64
    script: "make publish-manifests-lts-debian"
  - os: linux
    arch: amd64
    script: "make publish-manifests-lts-alpine"
  - os: linux
    arch: amd64
    script: "make publish-manifests-lts-slim"
  - os: linux
    arch: amd64
    script: "make publish-manifests-latest"
  - os: linux
    arch: amd64
    script: "make publish-manifests-versions"
env:
  global:
  - DOCKERHUB_ORGANISATION=jamescrowleyibm
  - DOCKERHUB_REPO=jenkins
