language: bash
sudo: required
services:
- docker
dist: xenial
jobs:
  include:
  - stage: Build Debian
    os: linux
    arch: s390x
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-debian"
  - os: linux
    arch: ppc64le
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-debian"
  - os: linux
    arch: amd64
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-debian"
  - os: linux
    arch: arm64
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-debian"
  - stage: Build Alpine
    os: linux
    arch: s390x
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-alpine"
  - os: linux
    arch: ppc64le
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-alpine"
  - os: linux
    arch: amd64
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-alpine"
  - os: linux
    arch: arm64
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-alpine"
  - stage: Build Slim
    os: linux
    arch: s390x
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-slim"
  - os: linux
    arch: ppc64le
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-slim"
  - os: linux
    arch: amd64
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-slim"
  - os: linux
    arch: arm64
    env: architecture=${TRAVIS_CPU_ARCH}
    script: "make publish-images-slim"
env:
  global:
  - DOCKERHUB_ORGANISATION=jenkins4eval
  - DOCKERHUB_REPO=jenkins