mongodb:
  image: mongo:3
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    - /data/db

jenkins:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000"
    - "8080"
  volumes:
    - /var/jenkins_home
  links:
    - mongodb

client1:
  extends:
    file: jnlp-slave/docker-compose.yml
    service: slave
  environment:
    slave: "myjnlpclient1"
  links:
    - jenkins
