version: '2'

services:

  jenkins:
    build: .
    privileged: true
    network_mode: "bridge"
    environment:
      - JAVA_OPTS=-Duser.timezone=Europe/Zurich
      - JENKINS_OPTS=''
      - JENKINS_EXECUTORS=7
      - JENKINS_BUILDSDIR=$${JENKINS_HOME}/builds/$${ITEM_FULL_NAME}
      - JENKINS_BOOTSTRAP_REPOSITORY=flavioaiello/jenkins
      - JENKINS_GITHUB_PRIVATE_KEY=''
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/jenkins/workspace:/var/jenkins_home/workspace
      - /data/jenkins/builds:/var/jenkins_home/builds
    ports:
        - "8080:8080"
    restart: always

