version: '2'
services:
  master:
    build:
      context: .
      args:
        - user=jenkins
        - group=jenkins
        - uid=1000
        - gid=1000
        - JENKINS_VERSION=2.0
        - JENKINS_SHA=da06f963edb627f0ced2fce612f9985d1928f79b
        - JENKINS_SLAVE_AGENT_PORT=50000
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /var/jenkins_home
