
version: '3.8'
services:
  jenkins:
    container_name: ${APP_CONTAINER_NAME}
    image: jenkins/jenkins${JENKINS_VERSION}
    ports:
     - ${APP_PORT}:8081
     - 50000:50000
    environment:
     - JAVA_OPTS=-Duser.timezone=Asia/Changsha
    #   JAVA_OPTS: "-Djava.awt.headless=true"

    restart: always
    volumes:
     - /volumes/data/jenkins:/var/jenkins_home
     - /var/jenkins_home/secrets/initialAdminPassword:/var/jenkins_home/secrets/initialAdminPassword
    #  - ./volumes/jenkins_home:/var/jenkins_home
    #  - ./volumes/jenkins-plugins:/usr/share/jenkins/ref/plugins

networks:
  default:
      name: "jenkins"
