


version: '3.8'
services:
  jenkins:
    container_name: jenkins-${JENKINS_VERSION}
    image: jenkins:${JENKINS_VERSION}
    ports:
     - '8080:8080'
     - '50000:50000'
    environment:
     - JAVA_OPTS=-Duser.timezone=Asia/changsha
    
    restart: always
    volumes:
     - '/volumes/data/jenkins:/var/jenkins_home
    #  - ./volumes/jenkins_home:/var/jenkins_home
    #  - ./volumes/jenkins-plugins:/usr/share/jenkins/ref/plugins
     
networks:
  default:
      name: "jenkins"
