version: '2'

services:

  jenkins:
    image: serverking/jenkins:latest
    privileged: true
    network_mode: "bridge"
    environment:
      - JAVA_OPTS=-Duser.timezone=Europe/Zurich
      - JENKINS_OPTS=''
      - EXECUTORS=7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/jenkins/builds:/var/jenkins_home/builds
      - /data/jenkins/workspaces:/var/jenkins_home/workspaces
    ports:
        - "8080:8080"
    restart: always

