jenkins:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000"
    - "8080"
  volumes:
    - /var/jenkins_home

client1:
  extends:
    file: jnlp-slave/docker-compose.yml
    service: slave
  environment:
    slave: "myjnlpclient1"
  links:
    - jenkins
