# this file from docker-compose.workspace, delete mail-server

version: '2'
services:
  jenkins:
    container_name: ${APP_CONTAINER_NAME}
    image: jenkins/jenkins:${JENKINS_VERSION}
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    # user: root
    # privileged: true
    restart: always
    ports:
      - "50000:50000"
      - "${APP_PORT}:8080"
    volumes:
      - ./volumes/data/jenkins:/var/jenkins_home
      - /var/jenkins_home/secrets:/var/jenkins_home/secrets

networks:
  default:
      name: ${APP_NETWORK}
